-- dnsdist configuration file, an example can be found in /usr/share/doc/dnsdist/examples/
newServer({address="193.0.14.129", healthCheckMode='up'})  -- k.root-servers.net (RIPE)
newServer({address="2001:7fd::1", healthCheckMode='up'})  -- k.root-servers.net (RIPE)

-- disable security status polling via DNS
setSecurityPollSuffix("")

-- listen on all interfaces
setLocal('0.0.0.0')
addLocal('::')

-- allow access from everywhere
setACL({"0.0.0.0/0", "::/0"})

-- log if something is wrong
setVerboseHealthChecks(true)

-- spoof priming responses
addAction(
    AndRule({QNameRule('.'), QTypeRule(DNSQType.NS)}),
    SpoofRawAction({"\001a\012w\048\048t\045servers\003net\000", "\001b\012w\048\048t\045servers\003net\000"}, { aa=true, ra=false, ttl=86400 })
)

-- Carbon statistics
carbonServer('37.252.122.50', 'desec-w00t-r')
