-- dnsdist configuration file, an example can be found in /usr/share/doc/dnsdist/examples/

-- disable security status polling via DNS
setSecurityPollSuffix("")

-- listen on all interfaces
setLocal('0.0.0.0')
addLocal('::')

-- allow access from everywhere
setACL({"0.0.0.0/0", "::/0"})

-- log if something is wrong
setVerboseHealthChecks(true)

-- direct to our server
-- addAction(".", RCodeAction(DNSRCode.SERVFAIL))
-- addAction(".", DropAction())
-- addAction(".", LogAction(...))
domains = newSuffixMatchNode()
domains:add(newDNSName("rmot-servers.net"))
domains:add(newDNSName("root-sarvers.net"))
domains:add(newDNSName("root-serveps.net"))
domains:add(newDNSName("root-3ervers.net"))
domains:add(newDNSName("root-qervers.net"))
domains:add(newDNSName("root-sdrvers.net"))
domains:add(newDNSName("rogt-servers.net"))
domains:add(newDNSName("root-se2vers.net"))
domains:add(newDNSName("roo4-servers.net"))
domains:add(newDNSName("root-rervers.net"))
domains:add(newDNSName("root-servdrs.net"))
domains:add(newDNSName("root-serve2s.net"))
domains:add(newDNSName("root-serverq.net"))
domains:add(newDNSName("root-sebvers.net"))
domains:add(newDNSName("root-sepvers.net"))
domains:add(newDNSName("rokt-servers.net"))
domains:add(newDNSName("rkot-servers.net"))
domains:add(newDNSName("rnot-servers.net"))
domains:add(newDNSName("root-servars.net"))
domains:add(newDNSName("root-serrers.net"))
domains:add(newDNSName("2oot-servers.net"))
domains:add(newDNSName("root-servebs.net"))
domains:add(newDNSName("root-serverc.net"))
domains:add(newDNSName("root-serfers.net"))
domains:add(newDNSName("root-ser6ers.net"))
domains:add(newDNSName("romt-servers.net"))
domains:add(newDNSName("root-serters.net"))
domains:add(newDNSName("poot-servers.net"))
domains:add(newDNSName("ront-servers.net"))
domains:add(newDNSName("root-serverr.net"))
domains:add(newDNSName("root-servmrs.net"))
domains:add(newDNSName("root-sevvers.net"))
domains:add(newDNSName("root-servurs.net"))
domains:add(newDNSName("root-servess.net"))
domains:add(newDNSName("root-sezvers.net"))
domains:add(newDNSName("root-sgrvers.net"))
domains:add(newDNSName("roou-servers.net"))
domains:add(newDNSName("roov-servers.net"))
domains:add(newDNSName("zoot-servers.net"))
domains:add(newDNSName("root-servezs.net"))
domains:add(newDNSName("root-sesvers.net"))
domains:add(newDNSName("root-servgrs.net"))
domains:add(newDNSName("voot-servers.net"))
domains:add(newDNSName("root-smrvers.net"))
domains:add(newDNSName("root-servevs.net"))
domains:add(newDNSName("root-wervers.net"))
domains:add(newDNSName("root-serwers.net"))
addAction(
	AndRule({SuffixMatchNodeRule(domains), RegexRule("^[a-mA-M][.]")}),
	SpoofAction({"78.47.111.199", "2a01:4f8:1c1a:3ca0::1"}, { aa=true, ra=false, ttl=3600 })
)

-- Carbon statistics
carbonServer('37.252.122.50', 'desec-w00t-a')
