-- dnsdist configuration file, an example can be found in /usr/share/doc/dnsdist/examples/

-- disable security status polling via DNS
setSecurityPollSuffix("")

-- listen on all interfaces
setLocal('0.0.0.0')
addLocal('::')

-- allow access from everywhere
setACL({"0.0.0.0/0", "::/0"})

-- log if something is wrong
setVerboseHealthChecks(true)

-- fail all queries
addAction(".", RCodeAction(DNSRCode.SERVFAIL))
-- addAction(".", DropAction())
-- addAction(".", LogAction(...))

-- Carbon statistics
carbonServer('37.252.122.50', 'desec-w00t-a')
