services:
  dnstap-capture:
    build: ./dnstap-capture
    command:
      - -s
      - "3600"
    volumes:
      - dnstap-socket:/run/dnstap
      - ./dnstap-spool:/spool/dnstap
    restart: unless-stopped

  uploader:
    build: ./uploader
    restart: unless-stopped
    environment:
      - RSYNC_DEST
      - INTERVAL_SECONDS=300
    volumes:
      - ./dnstap-spool:/spool/dnstap
      - ~/.ssh:/root/.ssh:ro

  knot:
    image: cznic/knot:mod-append-3.5
    command: knotd
    network_mode: host
    depends_on:
      - dnstap-capture
    volumes:
      - ./conf:/config
      - ./zones:/storage
      - dnstap-socket:/run/dnstap
    restart: unless-stopped

volumes:
  dnstap-socket:
