server:
    automatic-acl: on
    listen: [ 0.0.0.0@5353 ]

log:
  - target: syslog
    any: info

database:
    storage: /storage/

template:
  - id: default
    storage: /storage/

zone:
  - domain: .
    file: root.zone
