server:
    listen: 0.0.0.0@53
    listen: ::@53

mod-append:
  - id: custom
    zone: root-servers.net.
    a: 46.62.230.96
    aaaa: 2a01:4f9:c012:5daa::1
    labels: [ a, b, c, d, e, f, g, h, i, j, k, l, m ]

template:
  - id: default
    file: flip.zone
    storage: /storage/
    module: mod-append/custom
  - id: none

policy:
  - id: manual
    manual: on
    unsafe-operation: no-update-dnskey

zone:
  # cds-consistency
  - domain: cds-consistency.w00t-servers.net
    template: none
    file: cds-consistency.w00t-servers.net.zone
    storage: /storage/
    dnssec-signing: on
    dnssec-policy: manual

  # original
  - domain: root-servers.net
    template: none
    file: root-servers.net.zone
    storage: /storage/

  # registered by us
  - domain: rmot-servers.net
  - domain: root-sarvers.net
  - domain: root-serveps.net
  - domain: root-3ervers.net
  - domain: root-qervers.net
  - domain: root-sdrvers.net
  - domain: rogt-servers.net
  - domain: root-se2vers.net
  - domain: roo4-servers.net
  - domain: root-rervers.net
  - domain: root-servdrs.net
  - domain: root-serve2s.net
  - domain: root-serverq.net
  - domain: root-sebvers.net
  - domain: root-sepvers.net
  - domain: rokt-servers.net
  - domain: rkot-servers.net
  - domain: rnot-servers.net
  - domain: root-servars.net
  - domain: root-serrers.net
  - domain: 2oot-servers.net
  - domain: root-servebs.net
  - domain: root-serverc.net
  - domain: root-serfers.net
  - domain: root-ser6ers.net
  - domain: romt-servers.net
  - domain: root-serters.net
  - domain: poot-servers.net
  - domain: ront-servers.net
  - domain: root-serverr.net
  - domain: root-servmrs.net
  - domain: root-sevvers.net
  - domain: root-servurs.net
  - domain: root-servess.net
  - domain: root-sezvers.net
  - domain: root-sgrvers.net
  - domain: roou-servers.net
  - domain: roov-servers.net
  - domain: zoot-servers.net
  - domain: root-servezs.net
  - domain: root-sesvers.net
  - domain: root-servgrs.net
  - domain: voot-servers.net
  - domain: root-smrvers.net
  - domain: root-servevs.net
  - domain: root-wervers.net
  - domain: root-serwers.net
  - domain: root-serverw.net

  # registered by others
  - domain: root-server3.net
  - domain: roop-servers.net
  - domain: rgot-servers.net
  - domain: root-cervers.net
  - domain: rood-servers.net
  - domain: boot-servers.net
  - domain: root-survers.net
  - domain: soot-servers.net
