newServer({address="193.0.14.129", healthCheckMode='up'})  -- k.root-servers.net (RIPE)
newServer({address="2001:7fd::1", healthCheckMode='up'})  -- k.root-servers.net (RIPE)

newServer({address="127.0.0.1:5353", healthCheckMode='up', pool="priming"})

newServer({address="192.5.6.30", healthCheckMode='up', pool="gtld"})  -- a.gtld-servers.net
newServer({address="2001:502:1ca1::30", healthCheckMode='up', pool="gtld"})  -- e.gtld-servers.net
newServer({address="192.43.172.30", healthCheckMode='up', pool="gtld"})  -- i.gtld-servers.net
newServer({address="2001:501:b1f9::30", healthCheckMode='up', pool="gtld"})  -- m.gtld-servers.net

-- disable security status polling via DNS
setSecurityPollSuffix("")

-- listen on all interfaces
setLocal('0.0.0.0')
addLocal('::')

-- allow access from everywhere
setACL({"0.0.0.0/0", "::/0"})

-- log if something is wrong
setVerboseHealthChecks(true)

-- Log all queries/responses using dnstap
dtLogger = newFrameStreamUnixLogger("/run/dnstap/dnsdist.sock")
addAction(AllRule(), DnstapLogAction("dnsdist", dtLogger))
addResponseAction(AllRule(), DnstapLogResponseAction("dnsdist", dtLogger))

-- spoof priming responses
addAction(
    AndRule({QNameRule('.'), QTypeRule(DNSQType.NS)}),
    PoolAction('priming')
)

-- gtld-servers.net
addAction(
    NetmaskGroupRule({"95.217.245.237/32", "2a01:4f9:c012:5daa::aa/128", "46.225.255.84/32", "2a01:4f8:1c1a:3ca0::aa/128"}, false),
    PoolAction('gtld')
)

-- Carbon statistics
carbonServer('37.252.122.50', os.getenv("CARBON_INSTANCE"))
