newServer({address="193.0.14.129", healthCheckMode='up'})  -- k.root-servers.net (RIPE)
newServer({address="2001:7fd::1", healthCheckMode='up'})  -- k.root-servers.net (RIPE)

newServer({address="127.0.0.1:5353", healthCheckMode='up', pool="priming"})

-- disable security status polling via DNS
setSecurityPollSuffix("")

-- listen on all interfaces
setLocal('0.0.0.0')
addLocal('::')

-- allow access from everywhere
setACL({"0.0.0.0/0", "::/0"})

-- log if something is wrong
setVerboseHealthChecks(true)

-- Log all queries/responses using dnstap
dtLogger = newFrameStreamUnixLogger("/run/dnstap/dnsdist.sock")
addAction(AllRule(), DnstapLogAction("dnsdist", dtLogger))
addResponseAction(AllRule(), DnstapLogResponseAction("dnsdist", dtLogger))

-- spoof priming responses
addAction(
    AndRule({QNameRule('.'), QTypeRule(DNSQType.NS)}),
    PoolAction('priming')
)

-- Carbon statistics
carbonServer('37.252.122.50', os.getenv("CARBON_INSTANCE"))
